### ISSUE TITLE
参考文献格式的更改

### ISSUE THREAD

**Issue by Kingwen16** [liubenyuan/nudtpaper#13]
2018版科大论文模板的参考文献发生变化，新模板的参考文献为“”首字缩进两个字符，注意不是悬挂缩进“”，请问大神这个应该怎样修改啊？

**Comment by liubenyuan** [comment]
已经更改。

需要注意两点：
1、采用了enumitem包，源文件中enumerate和itemize环境需要更改。但是这个包会让你的列表环境更灵活。
2、学校具体格式没看见，“首字缩进两个字符，注意不是悬挂缩进”的要求基本满足了（这个审美。。。）。同时为了给科大的大神留余地，当参考文献数目超过100时首行缩进会稍微大一些。你们可以根据具体需要更改。

**Comment by Kingwen16** [comment]
感谢大神，之前没有说清楚，新版本生成的论文格式还是不符合规定。 这个PDF是学校2018对参考文献的规定样式，请大神再次指教，刚接触latex还是小白一枚。感谢感谢！
[组合 1.pdf](https://github.com/liubenyuan/nudtpaper/files/2648296/1.pdf)
