### ISSUE TITLE
请问交叉引用怎样引用汉字的章序号？

### ISSUE THREAD

**Issue by zhjsun** [liubenyuan/nudtpaper#14]
目前交叉引用章标题的label是阿拉伯数字形式，如“第1章”这种形式。但是章标题采用的是汉字，怎样在引用时也写成汉字形式，即“第一章”这种形式？

**Comment by liubenyuan** [comment]
我也没试过，你看看这个可以么
```latex
\renewcommand{\chaptername}{第\CJKnumber{\thechapter}章}
```

**Comment by zhjsun** [comment]
> 我也没试过，你看看这个可以么
> 
> ```
> \renewcommand{\chaptername}{第\CJKnumber{\thechapter}章}
> ```

这个只能修改标题的样式，在引用时编号仍然是阿拉伯数字。

**Comment by zhjsun** [comment]
添加如下命令可以解决。

`\makeatletter`
`\renewcommand\p@chapter{\zhnumber{\thechapter}\expandafter\@gobble}` 
`\makeatother`
