### ISSUE TITLE
模板未载入 enumitem 宏包， resume.tex 里用到了它的功能

### ISSUE THREAD

**Issue by muzimuzhi** [liubenyuan/nudtpaper#16]

**Comment by TaihuLight** [comment]
模板中说是在```mynudt.sty```中添加论文中使用专用红包，是不是在```mynudt.sty```的如下位置添加
```
% 这里添加你的论文中专门使用的宏包
\RequirePackage{enumitem}
% 原先preamble中的\usepackage{...}用\RequirePackage{...}代替
```
但是没有理解这里用\RequirePackage{...}和用\usepackage{...}有什么区别？

**Comment by liubenyuan** [comment]
我的理解两个是一样的。如果有缺少的宏包，在mynudt.sty中添加就好。

**Comment by muzimuzhi** [comment]
> 但是没有理解这里用\RequirePackage{...}和用\usepackage{...}有什么区别？

首先，相对于当前 issue，这是离题的问题。

然后，从语义上，文档类/宏包里用 `\Require...`，用户文档里用 `\usepackage`。这是一种约定，并不是语法上的强制约束。

最后，从语法上，唯一差异是 `\usepackage` 不能用于 `\documentclass` 之前，参见 [tex.sx 上的这个回答](https://tex.stackexchange.com/a/19929/79060)。

**Comment by muzimuzhi** [comment]
提这个 issue 的初衷是，
 - 模板提供的示例文档会编译出错，这是 bug，需要修复

**Comment by liubenyuan** [comment]
在`nudtpaper.cls`的第69行是默认加载`enumitem的` https://github.com/liubenyuan/nudtpaper/blob/9338501bfc2bf97acd57fa1105b661fe9b0456ef/nudtpaper.cls#L69

**Comment by muzimuzhi** [comment]
> 在2.3版本以后，所有修改直接在cls上了。
那就建议修改项目 README.md 了

**Comment by TaihuLight** [comment]
@muzimuzhi @liubenyuan 
https://github.com/CTeX-org/forum/issues/17
这个问题一并在这里讨论吧，就不新开一个issue了。

**Comment by mohuangrui** [comment]
@TaihuLight Adobe 中文字体下载可以网上公开获取，详见如下链接底部： https://github.com/mohuangrui/ucasthesis/wiki/字体配置

**Comment by TaihuLight** [comment]
（1）若字体公开获取的话，建议你将字体的下载和安装方法，加入到readme中。
（2）模板是否可以同时兼容pdfletex编译方式，因为maketex这个GUI对于这种编译方式支持比较好，而且这个GUI用的人也不少。

**Comment by muzimuzhi** [comment]
@TaihuLight 
你的回复明显离题了，请新建 issue 以展开讨论。
