### ISSUE TITLE
行距发送改变，行距明显变小

### ISSUE THREAD

**Issue by noplacenojason** [liubenyuan/nudtpaper#20]
偶尔有段落行距发生改变，明显减小
运行时提示cfg文件没有找到不知道是否是这个原因。

**Comment by liubenyuan** [comment]
是段与段之间么？跟cfg没关系，你可以把模板中parskip里的minus，plus语句删掉，只保留绝对距离。

**Comment by noplacenojason** [comment]
> 
> 
> 是段与段之间么？跟cfg没关系，你可以把模板中parskip里的minus，plus语句删掉，只保留绝对距离。

是行间距，不是段间距。我也很困惑。。。同学文章就没这个问题

**Comment by muzimuzhi** [comment]
需要提供可复现问题的完整例子。

**Comment by noplacenojason** [comment]
> 
> 
> 需要提供可复现问题
![warning](https://user-images.githubusercontent.com/55444969/65123937-f1b08280-da26-11e9-96f0-9b862f856282.png)
![warnings](https://user-images.githubusercontent.com/55444969/65123959-f9702700-da26-11e9-81d3-0c37d38421d4.png)
![warnings2](https://user-images.githubusercontent.com/55444969/65123966-fd03ae00-da26-11e9-990b-7c1ac2bc56ff.png)
前三幅图片为出现warning的部分信息，其他warning信息类似
![comparison](https://user-images.githubusercontent.com/55444969/65124012-1573c880-da27-11e9-8c38-69fdb05c9f1f.png)
从这幅图片可以看出在公式3.26之后行间距改变。公式3,26部分的代码和文字如下
-------
其中$W$为最小竞争窗口数值，$m$为最大退避阶数且$p^{cs}$为传输失败概率。由于节点未达成汇聚也会造成汇聚信息交互不成功， 因此$p^{cs}$可表示为
\begin{equation}
p^{cs} = 1 - (1- {P_c}) \cdot {P_{r}}
\end{equation}
其中$P_{r}$表示节点达成汇聚的概率（详情见3.4节）。
--------

**Comment by noplacenojason** [comment]
> 
> 
> 需要提供可复现问题的完整例子。

![warning](https://user-images.githubusercontent.com/55444969/65124827-97fc8800-da27-11e9-9279-b5de05ed29b3.png)
![warnings](https://user-images.githubusercontent.com/55444969/65124842-99c64b80-da27-11e9-9565-a85598c40858.png)
![warnings2](https://user-images.githubusercontent.com/55444969/65124856-9af77880-da27-11e9-9293-e6e742c28343.png)
前三幅图为编译后的部分warning信息，其他warning信息类似
![comparison](https://user-images.githubusercontent.com/55444969/65125063-b2366600-da27-11e9-9206-9cffaebb72c1.png)
这幅图可以明显看出从公式3.26后行距改变了。这部分文字和代码如下：
-------
其中$W$为最小竞争窗口数值，$m$为最大退避阶数且$p^{cs}$为传输失败概率。由于节点未达成汇聚也会造成汇聚信息交互不成功， 因此$p^{cs}$可表示为
\begin{equation}
p^{cs} = 1 - (1- {P_c}) \cdot {P_{r}}
\end{equation}
其中$P_{r}$表示节点达成汇聚的概率（详情见3.4节）。
----------

**Comment by noplacenojason** [comment]
> 
> 
> 需要提供可复现问题的完整例子。

所以不知道问题出在哪里

**Comment by noplacenojason** [comment]
解决了，在该段文字中使用\rm{P}而没有加限位符$

**Comment by muzimuzhi** [comment]
「可复现问题的完整例子」，需要是
1. 一个完整的、在你的电脑上能编译的 LaTeX 文档
     何为完整：以 `\documentclass` 开始，以 `\end{document}` 结束
2. 在你电脑上的编译结果，应当能复现你的问题
3. 与复现问题和体现需求无关的代码，应尽可能少

截图不是「完整例子」
