### ISSUE TITLE
请问如何更改参考文献中网址链接的字体？

### ISSUE THREAD

**Issue by AerosTJY** [liubenyuan/nudtpaper#21]
首先感谢各位师兄师姐辛苦维护这一模板，大大方便了我们的论文撰写。我这里在使用模板时，最后参考文献中包含的网址链接的字体和非链接的字体不一致，请问如何更改，能使得两者字体保持一致呢？

**Comment by liubenyuan** [comment]
我感觉需要修改bst文件。但是我不擅长这方面的内容，你可以尝试替换为这个bst
https://github.com/CTeX-org/gbt7714-bibtex-style
然后在这个作者下面问下他。这个也是符合规范的参考文献样式表。

**Comment by AerosTJY** [comment]
好的，感谢感谢！我先试试再说~~

**Comment by muzimuzhi** [comment]
1. 参考文献列表的内容，对应 `.bbl` 文件的内容
1. 从 `.bbl` 文件里可以看到，超链接是通过命令 `\url{...}` 标记的
1. `\url` 是 `url` 宏包提供的命令，它输出的内容的字体，受命令 `\urlstyle` 控制，参见 `url` 宏包文档第 3 节。

假设只需要修改参考文献列表中的超链接文本的字体，一种修改方式是
```latex
{\urlstyle{rm}
\bibliography{ref/refs}}
```
对应输出为
![image](https://user-images.githubusercontent.com/6376638/66703427-245b4b80-ed45-11e9-8c01-662e1b7558d6.png)


PS：超链接文本的颜色，是由 `hyperref` 宏包控制的。

**Comment by AerosTJY** [comment]
亲测有效，感谢大佬~~
