### ISSUE TITLE
I couldn't open file name `thesis.aux'

### ISSUE THREAD

**Issue by zlh004** [liubenyuan/nudtpaper#24]
您好。我在使用其他latex模板时未出现问题，但是在使用您的模板时出现了
![TIM截图20200303104618](https://user-images.githubusercontent.com/38122569/75738174-87716d00-5d3c-11ea-9ab4-9807a7056571.png)
从网上搜索了好多方法，还是没有解决。请问您知道怎么解决这个问题么

**Comment by liubenyuan** [comment]
好像第一次xelatex运行时没生成aux。你在命令行下运行xelatex thesis.tex,看有什么错误。

**Comment by zlh004** [comment]
感谢楼主，发现了问题。重装的系统，环境变量没有配置好。
但是现在发现了新的问题。就是我的系统已经安装了仿宋-GB2312字体，但是编译过后还是显示找不到这个字体
![TIM截图20200304093813](https://user-images.githubusercontent.com/38122569/75836155-e4802800-5dfb-11ea-9c60-baea359f5003.png)
如果楼主知道这种情况的话，还是麻烦解答一下。再次谢谢楼主

**Comment by zlh004** [comment]
从网上搜了一下，贴吧里面有人遇到了同样的情况，好像也没有解决http://tieba.baidu.com/p/5867005742?traceid=#
麻烦楼主了

**Comment by liubenyuan** [comment]
1、确定是xelatex编译，2、在命令行下用fc-list看下有无字体，字体名称是什么。3、用管理员方式重新安编字体。

可以现在stackexchange根据报错搜索，一般都有解决办法。

**Comment by zlh004** [comment]
感谢楼主，我把字体安装到系统里面，但是并没有加入到texlive当中。已解决，谢谢
