### ISSUE TITLE
This is XeTeX, Version 3.1415926-2.3-0.9997.5 (MiKTeX 2.9)

### ISSUE THREAD

**Issue by mengshanfeng** [liubenyuan/nudtpaper#33]
! LaTeX Error: File `zhnumber.sty' not found.

如题，请教各位大佬遇到这个错误怎么解决。

先谢过！

**Comment by hushidong** [comment]
说明你的tex发行版没有这个包。
你去ctan或者ctex. org下个放到当前目录就好了。

**Comment by mengshanfeng** [comment]
@hushidong 已解决，谢谢！
