### ISSUE TITLE
表格大小无法修改

### ISSUE THREAD

**Issue by liujiyuan13** [liubenyuan/nudtpaper#44]
\begin{table}[t]
\centering
\xiaoliu         // 使用\xiaosi，\tiny，\footnotesize 等一系列命令，表格均为产生任何变化
\caption{xxx}
\end{tabular}
\end{table}

**Comment by liubenyuan** [comment]
你试试放在table后面，tabular前面？

**Comment by liujiyuan13** [comment]
谢谢回复！还是不行的。最后我用下面方式解决了：

\begin{table}[t]
\centering
\caption{xxx}
\label{tab:opmc_time}
\resizebox{\linewidth}{!}{
\begin{tabular}{lcccccccccc}
\end{tabular} }
\end{table}

**Comment by liubenyuan** [comment]
这个里面没改字体呀。。。不过解决了就好~

**Comment by liujiyuan13** [comment]
没直接改字体大小，但是整体缩小了表格，导致字体也随着缩小了
