### ISSUE TITLE
协助指导老师数量大于1

### ISSUE THREAD

**Issue by AdamChangQi** [liubenyuan/nudtpaper#48]
尝试过在协助指导老师里面加入换行，会报错；
调用两边协助指导老师，第二个会将第一个冲刷覆盖

**Comment by liubenyuan** [comment]
这个需要在封面再加一行的，
https://github.com/liubenyuan/nudtpaper/blob/91c74a43ef5b89677a0300f540cae1e97fe710bb/nudtpaper.cls#L647
在这个后面你复制ifx和fi之间的，然后自己尝试修改下风格吧～

**Comment by AdamChangQi** [comment]
感谢感谢！根据您的建议我增添了一个cosupervisor2变量，问题解决了，顺便拜读了一下cls文件，再次向大佬致敬
\raisebox{-3.7ex}[0pt]{\makebox[3cm][s]{协\hfill{}助\hfill{}指\hfill{}导\hfill{}教\hfill{}师}} &
          {\fs \hfil\raisebox{-3.7ex}[0pt]{\@cosupervisor}\hfil{}} & \\[3.2ex]
          \cline{2-2}
          \raisebox{-3.7ex}[0pt]{\makebox[3cm][s]{}} &
          {\fs \hfil\raisebox{-3.7ex}[0pt]{\@cosupervisor2}\hfil{}} & \\[3.2ex]
          \cline{2-2}
      \fi
