### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by fofoview** [liubenyuan/nudtpaper#5]
您好，您的模板中对硕博论文引用后面是加标记[D]，如果要求出现博士学位论文字样该如何设置？
例如：XXX. 无线传感器网络地理位置路由协议 [D]. 长沙: 中南大学, 2014
如果要生成如下格式该如何修改？
XXX. 无线传感器网络地理位置路由协议 [D]. 硕士学位论文, 长沙: 中南大学，2014

**Comment by liubenyuan** [comment]
博士论文按照标准好像也是d。。。只要你把文献类型变为phd thesis就行

fofoview <notifications@github.com>于2016年7月17日 周日10:49写道：

**Comment by fofoview** [comment]
谢谢您！
