### ISSUE TITLE
关于i found no citation commands i found no bibdata command i found no bibstyle command的解决

### ISSUE THREAD

**Issue by YichuanSun** [liubenyuan/nudtpaper#53]
这个问题搞了两个多小时。

解决就是不要使用thesis.tex中提到的biber编译，老老实实用bibtex编译引用文献，编译过程xelatex->bibtex->xelatex->xelatex，别用biber替换bibtex。

我一开始看着提示里的文字描述的很好，就用了`\documentclass[master,biber,resumebib,fz]{nudtpaper}`，一直碰到上面这个错误，甚至引文全是问号。

后来换了`\documentclass[master,prof]{nudtpaper}`

又把`\addbibresource[location=local]{ref/refs.bib}`注释掉就没问题了。

因为这样设置的话编译文献没有用biber，因此会触发底下
`\else`
`\bibliographystyle{bstutf8}`
`\bibliography{ref/refs}`
`\fi`
的逻辑，因此引用文献还是从refs里面读，所以注释掉那行不会出错。

-------------
首先感谢一下多年前的老学长本源哥，有了这套模板，我们的毕业论文漂亮干净了很多很多。

但是这个模板大大小小的问题真的挺多的，比如这个问题，以及字体问题，等等，而且跟ieee的模板风格差别较大，之前用latex写过几篇paper，但还是花了整整三天才把word上的大约25000字内容迁移过来，各种格式问题调起来有点棘手。

大家碰到什么棘手的问题，也多过来提一提，帮助完善使用体验，从而能帮助更多六院人，更多科大人。

**Comment by hushidong** [comment]
习惯用bibtex就把biber选项去掉即可？

加了biber选项，就要用biber编译，再加了resumebib选项可以让你的成果表能用bib的形式来组织，而不必自己手动来写了。

两个路子都要有，这也是方便大家的。头部学校的模板大多都是两个路子都有，如清华，复旦，中科大，中科院，甚至少部分只有biber，如浙大，上交的。
