### ISSUE TITLE
“独创性声明”和“学位论文版权使用授权书”如何导入手写签名呢？

### ISSUE THREAD

**Issue by Longing0526** [liubenyuan/nudtpaper#56]
“独创性声明”和“学位论文版权使用授权书”如何导入手写签名呢？明评版论文需要，谢谢！

**Comment by liubenyuan** [comment]
> 我在这里自问自答了嗷，可以在pdf文件里处理，然后再替换掉这一页。

是的，我们那会都用pdftk替换一下
