### ISSUE TITLE
关于目录页中页码字体的问题

### ISSUE THREAD

**Issue by DoTulip** [liubenyuan/nudtpaper#62]
在学校模板中，目录页的“摘要”、“Abstract”和每一章题目对应页码的字体是Arial。在latex模板中，所有页码用的字体都是Times。请问如何更改呢？图1为学校模板，图2为latex模板
![2024-11-16 17 13 44](https://github.com/user-attachments/assets/a74adf73-f5d7-43c7-aebc-2fd812e685db)
![2024-11-16 17 14 13](https://github.com/user-attachments/assets/e87181d3-e8c0-4a56-aa7f-291449318143)

**Comment by hushidong** [comment]
如果教务没有要求就不用改。

从24年6月提交的论文看，学院学校都没有提出异议。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: TTT ***@***.***>
Sent: Saturday, November 16, 2024 5:22:55 PM
To: liubenyuan/nudtpaper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liubenyuan/nudtpaper] 关于目录页中页码字体的问题 (Issue #62)


在学校模板中，目录页的“摘要”、“Abstract”和每一章题目对应页码的字体是Arial。在latex模板中，所有页码用的字体都是Times。请问如何更改呢？图1为学校模板，图2为latex模板
2024-11-16.17.13.44.png (view on web)<https://github.com/user-attachments/assets/a74adf73-f5d7-43c7-aebc-2fd812e685db>
2024-11-16.17.14.13.png (view on web)<https://github.com/user-attachments/assets/e87181d3-e8c0-4a56-aa7f-291449318143>

―

**Comment by DoTulip** [comment]
我看了之前上传的毕业论文，用latex写作的和目前模板一致。不过我在送评阅和申请答辩时2次被学院教务指出了这里字体有误。

**Comment by DoTulip** [comment]
我看了之前上传的毕业论文，用latex写作的和目前模板一致。不过我在送评阅和申请答辩时2次被学院教务指出了这里字体有误。

**Comment by hushidong** [comment]
那就做修改。

是哪个学院的？

如果不该cls
那么在导言区添加如下代码：

```
\makeatletter
\newcommand{\ftArial}{\fontspec{Arial}\selectfont}
\renewcommand\contentspage[1][\thecontentspage]{%
  \hb@xt@\@pnumwidth{\hfil\ftArial{#1}}%
  \hspace*{-\@pnumwidth}}
\makeatother

```

结果为；

![图片](https://github.com/user-attachments/assets/de95f309-5ae8-414d-a8c8-700b587fdb1e)

**Comment by DoTulip** [comment]
感谢大神！航院的。
还有一点小问题，只有一级标题对应的页码是Arial，其它的还是Times

**Comment by DoTulip** [comment]
已通过修改cls文件解决，此问题关闭
