### ISSUE TITLE
pdf里的超链接

### ISSUE THREAD

**Issue by glingli** [liubenyuan/nudtpaper#64]
请问pdf里目录、图和表的蓝色的超链接在打印的时候颜色可以取消掉吗
![qqqqqqqqqq](https://github.com/user-attachments/assets/7f91b86f-9b74-48e4-97b0-e46b010cf544)

**Comment by yagdig** [comment]
可以在nudtpaper.cls文件82行，hyperref宏包设置里更改，重新编译打印。

**Comment by glingli** [comment]
感谢，顺便更正一下，是nudtpaper.cls内的这个语句：
```
\RequirePackage[colorlinks=true,linkcolor=blue,citecolor=red,bookmarksnumbered=true,pdfborder=0 1 1]{hyperref}
```
将`colorlinks`参数设置为false即可。
